/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormConsultaProduto.java
 *
 * Created on 10/02/2010, 22:17:41
 */

package br.com.bijufactory.ui;

import br.com.bijufactory.produto.controller.ProdutoController;
import br.com.bijufactory.produto.model.BjProduto;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FormConsultaProduto extends javax.swing.JFrame {
    String[][] dados = null;
    String[] colunas;
    private DefaultTableModel modelo;
    ProdutoController produtoController;

    /** Creates new form FormConsultaProduto */
    public FormConsultaProduto() {
        initComponents();
        produtoController = new ProdutoController();

        //dados = new String [][]{
        //             {"SP","Sao Paulo"},
        //             {"RJ","Rio de Janeiro"},
        //             {"RN","Rio Grande do Norte"},
        //             {"PR","Parana"}
        //};
        colunas = new String []{"Cod. Produto","Descrição","Quant.","Preço Unit.", "%Desc", "Sub. Total", "%ICMS", "%Base ICMS", "Vlr. ICMS"};
        // Ao inves de passar direto, colocamos os dados em um modelo
        modelo = new DefaultTableModel(colunas, 0);
        // e passamos o modelo para criar a jtable
        jTableConsultaProduto.setModel( this.modelo);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelProduto = new javax.swing.JLabel();
        TxSCodigoProduto = new javax.swing.JTextField();
        jToggleButtonConsultar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultaProduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));

        jLabelProduto.setText("Produto:");

        jToggleButtonConsultar.setText("Consultar");
        jToggleButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TxSCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                        .addComponent(jToggleButtonConsultar))
                    .addComponent(jLabelProduto))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonConsultar)
                    .addComponent(TxSCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTableConsultaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableConsultaProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonConsultarActionPerformed

        //String msg = fornecedorMateriaPrimaController.validaFornecedor(sCodigoFornecedor);
        //if(this.getTxSCodigoProduto().toString() != null && !this.getTxSCodigoProduto().toString().equals("")){
        //    JOptionPane.showMessageDialog(rootPane, "blablabla");
        //}else{
            //this.habilitaComponentes(true);
            //this.getTxSCodigoMateriaPrima().grabFocus();
            ArrayList collectionProduto = new ArrayList();
            collectionProduto = (ArrayList) produtoController.listaTudo();
            if (collectionProduto != null){
                Iterator i = collectionProduto.iterator();
                while(i.hasNext()){
                    BjProduto bjProduto = (BjProduto)i.next();
                    String[] row = new String []{bjProduto.getSCodigo().toString(),
                                                 bjProduto.getSDescricao().toString()};
                    this.modelo.addRow(row);
                }
            }

        //}
    }//GEN-LAST:event_jToggleButtonConsultarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxSCodigoProduto;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultaProduto;
    private javax.swing.JToggleButton jToggleButtonConsultar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the TxSCodigoProduto
     */
    public javax.swing.JTextField getTxSCodigoProduto() {
        return TxSCodigoProduto;
    }

    /**
     * @param TxSCodigoProduto the TxSCodigoProduto to set
     */
    public void setTxSCodigoProduto(javax.swing.JTextField TxSCodigoProduto) {
        this.TxSCodigoProduto = TxSCodigoProduto;
    }

}
