/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormCadastroProdutos.java
 *
 * Created on 24/09/2009, 14:25:10
 */

package br.com.bijufactory.ui;

import br.com.bijufactory.produto.controller.ProdutoController;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FormCadastroProdutos extends javax.swing.JFrame {
    ProdutoController produtoController;
    
    /** Creates new form FormCadastroProdutos */
    public FormCadastroProdutos() {
        initComponents();
        produtoController = new ProdutoController();
        this.limpaComponetes();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void habilitaComponentes(boolean status){
        this.txNIndiceAuAg.setEnabled(status);
        this.txNPeso.setEnabled(status);
        this.txNVlrCusto.setEnabled(status);
        this.txSDescricao.setEnabled(status);

        this.btSalvar.setEnabled(status);
        this.btExcluir.setEnabled(status);
        this.btAbrirImagem.setEnabled(status);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txNIndiceAuAg = new javax.swing.JTextField();
        lbIndiceAuAg = new javax.swing.JLabel();
        lbNVlrCusto = new javax.swing.JLabel();
        txNVlrCusto = new javax.swing.JTextField();
        txNPeso = new javax.swing.JTextField();
        lbNPeso = new javax.swing.JLabel();
        lbSDescricao = new javax.swing.JLabel();
        txSDescricao = new javax.swing.JTextField();
        txSCodigo = new javax.swing.JTextField();
        lbSCodigo = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JToggleButton();
        btNovo = new javax.swing.JToggleButton();
        btExcluir = new javax.swing.JToggleButton();
        btSalvar = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        btAbrirImagem = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produto");
        setBounds(new java.awt.Rectangle(450, 300, 0, 0));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Produto"));

        lbIndiceAuAg.setText("Indice AU/AG:");

        lbNVlrCusto.setText("Valor Custo:");

        txNVlrCusto.setBackground(new java.awt.Color(255, 255, 153));

        lbNPeso.setText("Peso");

        lbSDescricao.setText("Descricao:");

        txSDescricao.setBackground(new java.awt.Color(255, 255, 153));

        txSCodigo.setBackground(new java.awt.Color(255, 255, 153));
        txSCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSCodigoActionPerformed(evt);
            }
        });

        lbSCodigo.setText("Codigo:");

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSDescricao)
                    .addComponent(lbNPeso)
                    .addComponent(lbIndiceAuAg)
                    .addComponent(lbSCodigo)
                    .addComponent(lbNVlrCusto, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txNIndiceAuAg, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txNVlrCusto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txSCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPesquisar))
                    .addComponent(txSDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txSCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSCodigo)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txSDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNPeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNVlrCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNVlrCusto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNIndiceAuAg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIndiceAuAg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bijufactory/resources/img_adicionar0.gif"))); // NOI18N
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bijufactory/resources/ico_excluir.gif"))); // NOI18N
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bijufactory/resources/salvar.png"))); // NOI18N
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagem"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );

        btAbrirImagem.setText("Abrir");
        btAbrirImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirImagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(btAbrirImagem))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(btSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btNovo))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAbrirImagem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpaComponetes(){
        this.txNIndiceAuAg.setText("");
        this.txNPeso.setText("");
        this.txNVlrCusto.setText("");
        this.txSDescricao.setText("");
        produtoController.inicializaObjetos();
        this.habilitaComponentes(false);
        this.txSCodigo.grabFocus();
    }

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        this.habilitaComponentes(true);
        this.limpaComponetes();
        produtoController.inicializaObjetos();
}//GEN-LAST:event_btNovoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        Object opcoes[] = {"Sim","Não"};
        //JDialog.setDefaultLookAndFeelDecorated(true);
        int op = JOptionPane.showOptionDialog(null, "Confirma a exclusão do produto?", "Excluindo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE , null, opcoes, null);
        if(op == JOptionPane.YES_OPTION ){
            produtoController.removerProduto();
            this.limpaComponetes();
        }
}//GEN-LAST:event_btExcluirActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Object opcoes[] = {"Sim","Não"};
        //JDialog.setDefaultLookAndFeelDecorated(true);
        int op = JOptionPane.showOptionDialog(null, "Confirma a gravação da produto?", "Gravando", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE , null, opcoes, null);
        if(op == JOptionPane.YES_OPTION ){
            produtoController.getBjProduto().setSCodigo(this.getTxSCodigo().getText());
            produtoController.getBjProduto().setSDescricao(this.getTxSDescricao().getText());
            produtoController.getBjProduto().setNVlrCusto(Double.parseDouble(this.getTxNVlrCusto().getText()));
            produtoController.getBjProduto().setNPeso(Double.parseDouble(this.getTxNPeso().getText()));
            produtoController.getBjProduto().setNIndiceAuAg(this.getTxNIndiceAuAg().getText());

            produtoController.salvar();
        }
}//GEN-LAST:event_btSalvarActionPerformed

    private void txSCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSCodigoActionPerformed
        produtoController.inicializaObjetos();
        this.limpaComponetes();
        this.habilitaComponentes(true);
        produtoController.consultarProduto(getTxSCodigo().getText());
        getTxNIndiceAuAg().setText(produtoController.getBjProduto().getNIndiceAuAg());
        getTxSDescricao().setText(produtoController.getBjProduto().getSDescricao());
        getTxNPeso().setText(produtoController.getBjProduto().getNPeso().toString());
        getTxNVlrCusto().setText(produtoController.getBjProduto().getNVlrCusto().toString());


        Image img = Toolkit.getDefaultToolkit().createImage(
            produtoController.getBjProduto().getImagem().toString().getBytes());

        ImageIcon icon = new ImageIcon(img);
        this.imageLabel.setIcon(icon);
    }//GEN-LAST:event_txSCodigoActionPerformed

    private void btAbrirImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirImagemActionPerformed

        
        JFileChooser arquivo = new JFileChooser();
        int result = arquivo.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            BufferedImage imagem = null;
            try {
                imagem = ImageIO.read(arquivo.getSelectedFile());
            } catch (IOException ex) {
                Logger.getLogger(FormCadastroProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
            int w = imagem.getWidth();
            int h = imagem.getHeight();

            ImageIcon icon = new ImageIcon(imagem);
            this.imageLabel.setIcon(icon);

            FileInputStream img = null;
            try {
                img = new FileInputStream(arquivo.getSelectedFile());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FormCadastroProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
            produtoController.getBjProduto().setImagem(img);
            //int[] pixels = imagem.getRGB(0, 0, w, h, null, 0, w);
            //Random r = new Random();

            //for (int col = 0; col < w; col++) {
            //  for (int lin = 0; lin < h; lin++) {
            //    pixels[w * lin + col] =
            //      new Color(r.nextInt(255), col % 255, lin % 255).getRGB();
            //  }
            //}

            //imagem.setRGB(0, 0, w, h, pixels, 0, w);
            //ImageIO.write(imagem, "PNG", new File("arteabstrata.png"));
        }
    }//GEN-LAST:event_btAbrirImagemActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
         new FormConsultaProduto().setVisible(true);
    }//GEN-LAST:event_btPesquisarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btAbrirImagem;
    private javax.swing.JToggleButton btExcluir;
    private javax.swing.JToggleButton btNovo;
    private javax.swing.JToggleButton btPesquisar;
    private javax.swing.JToggleButton btSalvar;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbIndiceAuAg;
    private javax.swing.JLabel lbNPeso;
    private javax.swing.JLabel lbNVlrCusto;
    private javax.swing.JLabel lbSCodigo;
    private javax.swing.JLabel lbSDescricao;
    private javax.swing.JTextField txNIndiceAuAg;
    private javax.swing.JTextField txNPeso;
    private javax.swing.JTextField txNVlrCusto;
    private javax.swing.JTextField txSCodigo;
    private javax.swing.JTextField txSDescricao;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the txNIndiceAuAg
     */
    public javax.swing.JTextField getTxNIndiceAuAg() {
        return txNIndiceAuAg;
    }

    /**
     * @param txNIndiceAuAg the txNIndiceAuAg to set
     */
    public void setTxNIndiceAuAg(javax.swing.JTextField txNIndiceAuAg) {
        this.txNIndiceAuAg = txNIndiceAuAg;
    }

    /**
     * @return the txNPeso
     */
    public javax.swing.JTextField getTxNPeso() {
        return txNPeso;
    }

    /**
     * @param txNPeso the txNPeso to set
     */
    public void setTxNPeso(javax.swing.JTextField txNPeso) {
        this.txNPeso = txNPeso;
    }

    /**
     * @return the txNVlrCusto
     */
    public javax.swing.JTextField getTxNVlrCusto() {
        return txNVlrCusto;
    }

    /**
     * @param txNVlrCusto the txNVlrCusto to set
     */
    public void setTxNVlrCusto(javax.swing.JTextField txNVlrCusto) {
        this.txNVlrCusto = txNVlrCusto;
    }

    /**
     * @return the txSCodigo
     */
    public javax.swing.JTextField getTxSCodigo() {
        return txSCodigo;
    }

    /**
     * @param txSCodigo the txSCodigo to set
     */
    public void setTxSCodigo(javax.swing.JTextField txSCodigo) {
        this.txSCodigo = txSCodigo;
    }

    /**
     * @return the txSDescricao
     */
    public javax.swing.JTextField getTxSDescricao() {
        return txSDescricao;
    }

    /**
     * @param txSDescricao the txSDescricao to set
     */
    public void setTxSDescricao(javax.swing.JTextField txSDescricao) {
        this.txSDescricao = txSDescricao;
    }

}
