/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormCadastroCotacao.java
 *
 * Created on 24/09/2009, 15:06:44
 */

package br.com.bijufactory.ui;

import br.com.bijufactory.cotacao.controller.CotacaoController;
import br.com.bijufactory.cotacao.model.BjCotacao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FormCadastroCotacao extends javax.swing.JFrame {
    CotacaoController fornecedorMateriaPrimaController;
    String[][] dados = null;
    String[] colunas;
    private DefaultTableModel modelo;

    /** Creates new form FormCadastroCotacao */
    public FormCadastroCotacao() {
        initComponents();


        this.limpaComponentes();
        this.txSCodigoFornecedor.setToolTipText("Informe o código do fornecedor");
        this.txSCodigoMateriaPrima.setToolTipText("Informe o código da matéria prima");
        this.btAdd.setToolTipText("Adicionar materia prima");
        this.btExcluir.setToolTipText("Excluir formula");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txSCodigoFornecedor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txSCodigoMateriaPrima = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFornecedorMateriaPrima = new javax.swing.JTable();
        btAdd = new javax.swing.JToggleButton();
        btRemover = new javax.swing.JToggleButton();
        txValorCusto = new javax.swing.JFormattedTextField();
        btSalvar = new javax.swing.JToggleButton();
        btExcluir = new javax.swing.JToggleButton();
        btNovo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Fornecedor"));

        jLabel1.setText("Codigo Fornecedor:");

        txSCodigoFornecedor.setBackground(new java.awt.Color(255, 255, 153));
        txSCodigoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSCodigoFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(txSCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txSCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Matéria Prima"));

        jLabel3.setText("Cod. Matéria Prima:");

        txSCodigoMateriaPrima.setBackground(new java.awt.Color(255, 255, 153));
        txSCodigoMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSCodigoMateriaPrimaActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor Custo:");

        tableFornecedorMateriaPrima.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableFornecedorMateriaPrima);

        btAdd.setText("add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btRemover.setText("remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        txValorCusto.setBackground(new java.awt.Color(255, 255, 153));
        txValorCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSCodigoMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(296, 296, 296))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemover)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txSCodigoMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btRemover))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bijufactory/resources/salvar.png"))); // NOI18N
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bijufactory/resources/ico_excluir.gif"))); // NOI18N
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bijufactory/resources/img_adicionar0.gif"))); // NOI18N
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(btSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void habilitaComponentes(boolean status){
        this.getTxSCodigoMateriaPrima().setEnabled(status);
        this.getTxValorCusto().setEnabled(status);

        this.btAdd.setEnabled(status);
        this.btRemover.setEnabled(status);
        this.btSalvar.setEnabled(status);
        this.btExcluir.setEnabled(status);
        //this.btNovo.setEnabled(status);
    }

    private void limpaComponentes(){
        this.getTxSCodigoFornecedor().setText("");
        this.getTxSCodigoMateriaPrima().setText("");
        this.getTxValorCusto().setValue(0);

        fornecedorMateriaPrimaController = new CotacaoController();
        dados = new String [][]{
            {"",""}
        };

        //dados = new String [][]{
        //             {"SP","Sao Paulo"},
        //             {"RJ","Rio de Janeiro"},
        //             {"RN","Rio Grande do Norte"},
        //             {"PR","Parana"}
        //};
        colunas = new String []{"Cod. Materia Prima","Vlr. Custo"};
        // Ao inves de passar direto, colocamos os dados em um modelo
        modelo = new DefaultTableModel(colunas, 0);
        // e passamos o modelo para criar a jtable
        tableFornecedorMateriaPrima.setModel( getModelo());

        fornecedorMateriaPrimaController.inicializaObjetos();
        this.habilitaComponentes(false);
        this.getTxSCodigoFornecedor().grabFocus();
    }

    private void txSCodigoMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSCodigoMateriaPrimaActionPerformed
        txValorCusto.grabFocus();
    }//GEN-LAST:event_txSCodigoMateriaPrimaActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Object opcoes[] = {"Sim","Não"};
        //JDialog.setDefaultLookAndFeelDecorated(true);
        int op = JOptionPane.showOptionDialog(null, "Confirma a gravação do fornecedor materia prima?", "Gravando", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE , null, opcoes, null);
        if(op == JOptionPane.YES_OPTION ){
            fornecedorMateriaPrimaController.salvar(this);
        }
        //this.limpaComponetes();
}//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        Object opcoes[] = {"Sim","Não"};
        //JDialog.setDefaultLookAndFeelDecorated(true);
        int op = JOptionPane.showOptionDialog(null, "Confirma a exclusão da formula?", "Excluindo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE , null, opcoes, null);
        if(op == JOptionPane.YES_OPTION ){

            ArrayList collectionFornecedorMateriPrima = new ArrayList();
            collectionFornecedorMateriPrima = fornecedorMateriaPrimaController.getCollectionFornecedorMateriaPrima();
            fornecedorMateriaPrimaController.setCollectionFornecedorMateriaPrimaRemoved(collectionFornecedorMateriPrima);

            fornecedorMateriaPrimaController.removerFornecedorMateriaPrima();
            this.limpaComponentes();
        }
}//GEN-LAST:event_btExcluirActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        this.habilitaComponentes(false);
        this.limpaComponentes();
}//GEN-LAST:event_btNovoActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        // Obtem a linha selecionada na tabela e chama o método
        // para excluir a linha
        int linhaSelecionada = tableFornecedorMateriaPrima.getSelectedRow();

        // Verificamos se existe realmente alguma linha selecionada
        if( linhaSelecionada < 0 ){
            return;
        }else{
            // Remove a linha do modelo
            fornecedorMateriaPrimaController.addCollectionFormulaRemoved(getModelo().getValueAt(linhaSelecionada, 0).toString());
            fornecedorMateriaPrimaController.removerCollectionFormula(getModelo().getValueAt(linhaSelecionada, 0).toString(), getModelo().getValueAt(linhaSelecionada, 1).toString());
            System.out.println(getModelo().getValueAt(linhaSelecionada, 0).toString());
            getModelo().removeRow(linhaSelecionada);
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        if(getTxSCodigoFornecedor().getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Código do fornecedor não informado!");
        }else{
            String msg = fornecedorMateriaPrimaController.validaFornecedor(getTxSCodigoFornecedor().getText());
            if(msg != null && !msg.equals("")){
                JOptionPane.showMessageDialog(rootPane, msg);
            }else{
                if(Integer.parseInt(getTxValorCusto().getValue().toString()) < 1){
                    JOptionPane.showMessageDialog(rootPane, "A quantidade não pode ser menor que [ 1 ] !");
                }else{
                    if(this.getTxSCodigoMateriaPrima().getText().equals("")){
                        JOptionPane.showMessageDialog(rootPane, "Código da matéria prima não informado!");
                    }else{
                        msg = fornecedorMateriaPrimaController.validaMateriaPrima(getTxSCodigoMateriaPrima().getText());
                        if(msg != null && !msg.equals("")){
                            JOptionPane.showMessageDialog(rootPane, msg);
                        }else{
                            String[] row = new String []{getTxSCodigoMateriaPrima().getText(),getTxValorCusto().getValue().toString()};
                            getModelo().addRow(row);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void txSCodigoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSCodigoFornecedorActionPerformed
        String sCodigoFornecedor = this.getTxSCodigoFornecedor().getText();
        this.limpaComponentes();
        this.getTxSCodigoFornecedor().setText(sCodigoFornecedor);
        String msg = fornecedorMateriaPrimaController.validaFornecedor(sCodigoFornecedor);
        if(msg != null && !msg.equals("")){
            JOptionPane.showMessageDialog(rootPane, msg);
        }else{
            this.habilitaComponentes(true);
            this.getTxSCodigoMateriaPrima().grabFocus();
            ArrayList collectionFornecedorMateriaPrima = new ArrayList();
            collectionFornecedorMateriaPrima = fornecedorMateriaPrimaController.validaFornecedorMateriaPrima();
            if (collectionFornecedorMateriaPrima != null){
                Iterator i = collectionFornecedorMateriaPrima.iterator();
                while(i.hasNext()){
                    BjCotacao bjFornecedorMateriaPrima = (BjCotacao)i.next();
                    String[] row = new String []{bjFornecedorMateriaPrima.getSCodigoMateriaPrima().getSCodigo(),
                                                 bjFornecedorMateriaPrima.getnValorCusto().toString()};
                    getModelo().addRow(row);
                }
            }

        }
    }//GEN-LAST:event_txSCodigoFornecedorActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroCotacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btAdd;
    private javax.swing.JToggleButton btExcluir;
    private javax.swing.JToggleButton btNovo;
    private javax.swing.JToggleButton btRemover;
    private javax.swing.JToggleButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFornecedorMateriaPrima;
    private javax.swing.JTextField txSCodigoFornecedor;
    private javax.swing.JTextField txSCodigoMateriaPrima;
    private javax.swing.JFormattedTextField txValorCusto;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the modelo
     */
    public DefaultTableModel getModelo() {
        return modelo;
    }

    /**
     * @return the txSCodigoFornecedor
     */
    public javax.swing.JTextField getTxSCodigoFornecedor() {
        return txSCodigoFornecedor;
    }

    /**
     * @param txSCodigoFornecedor the txSCodigoFornecedor to set
     */
    public void setTxSCodigoFornecedor(javax.swing.JTextField txSCodigoFornecedor) {
        this.txSCodigoFornecedor = txSCodigoFornecedor;
    }

    /**
     * @return the txSCodigoMateriaPrima
     */
    public javax.swing.JTextField getTxSCodigoMateriaPrima() {
        return txSCodigoMateriaPrima;
    }

    /**
     * @param txSCodigoMateriaPrima the txSCodigoMateriaPrima to set
     */
    public void setTxSCodigoMateriaPrima(javax.swing.JTextField txSCodigoMateriaPrima) {
        this.txSCodigoMateriaPrima = txSCodigoMateriaPrima;
    }

    /**
     * @return the txValorCusto
     */
    public javax.swing.JFormattedTextField getTxValorCusto() {
        return txValorCusto;
    }

    /**
     * @param txValorCusto the txValorCusto to set
     */
    public void setTxValorCusto(javax.swing.JFormattedTextField txValorCusto) {
        this.txValorCusto = txValorCusto;
    }

}
