/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormCadastroFormula.java
 *
 * Created on 24/09/2009, 14:25:42
 */

package br.com.bijufactory.ui;

import br.com.bijufactory.formula.controller.FormulaController;
import br.com.bijufactory.formula.model.BjFormula;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FormCadastroFormula extends javax.swing.JFrame {
    FormulaController formulaController;
    String[][] dados = null;
    String[] colunas;
    private DefaultTableModel modelo;

    /** Creates new form FormCadastroFormula */
    public FormCadastroFormula() {
        initComponents();

        this.limpaComponetes();
        this.txSCodigoProduto.setToolTipText("Informe o código do produto");
        this.txSCodigoMateriaPrima.setToolTipText("Informe o código da matéria prima");
        this.btAdd.setToolTipText("Adicionar materia prima");
        this.btExcluir.setToolTipText("Excluir formula");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbSCodigoProduto = new javax.swing.JLabel();
        txSCodigoProduto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txSCodigoMateriaPrima = new javax.swing.JTextField();
        lbSCodigoMateriaPrima = new javax.swing.JLabel();
        lbQuantidade = new javax.swing.JLabel();
        txQuantidade = new javax.swing.JSpinner();
        btAdd = new javax.swing.JToggleButton();
        btRemover = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFormulaProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btNovo = new javax.swing.JToggleButton();
        btExcluir = new javax.swing.JToggleButton();
        btSalvar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Formula Produto");
        setBounds(new java.awt.Rectangle(450, 300, 0, 0));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Formula"));

        lbSCodigoProduto.setText("Cod. Produto:");

        txSCodigoProduto.setBackground(new java.awt.Color(255, 255, 153));
        txSCodigoProduto.setToolTipText("");
        txSCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSCodigoProdutoActionPerformed(evt);
            }
        });
        txSCodigoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txSCodigoProdutoFocusLost(evt);
            }
        });
        txSCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txSCodigoProdutoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txSCodigoProdutoKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Matérias Primas que compõe a formula"));

        txSCodigoMateriaPrima.setBackground(new java.awt.Color(255, 255, 153));
        txSCodigoMateriaPrima.setEnabled(false);
        txSCodigoMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSCodigoMateriaPrimaActionPerformed(evt);
            }
        });

        lbSCodigoMateriaPrima.setText("Cod. Matéria Prima:");

        lbQuantidade.setText("Quantidade:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSCodigoMateriaPrima)
                    .addComponent(lbQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txSCodigoMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSCodigoMateriaPrima)
                    .addComponent(txSCodigoMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantidade)
                    .addComponent(txQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btAdd.setText("add");
        btAdd.setEnabled(false);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btRemover.setText("remover");
        btRemover.setEnabled(false);
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        tbFormulaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbFormulaProduto.setDragEnabled(true);
        tbFormulaProduto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbFormulaProduto);

        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        jLabel1.setText("[ENTER]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lbSCodigoProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txSCodigoProduto)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRemover))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSCodigoProduto)
                    .addComponent(txSCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRemover)
                    .addComponent(btAdd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bijufactory/resources/img_adicionar0.gif"))); // NOI18N
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bijufactory/resources/ico_excluir.gif"))); // NOI18N
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bijufactory/resources/salvar.png"))); // NOI18N
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(btSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE))
                    .addComponent(btNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void habilitaComponentes(boolean status){
        this.txSCodigoMateriaPrima.setEnabled(status);
        this.txQuantidade.setEnabled(status);

        this.btAdd.setEnabled(status);
        this.btRemover.setEnabled(status);
        this.btSalvar.setEnabled(status);
        this.btExcluir.setEnabled(status);
        //this.btNovo.setEnabled(status);
    }

    private void limpaComponetes(){
        this.txSCodigoProduto.setText("");
        this.txSCodigoMateriaPrima.setText("");
        this.txQuantidade.setValue(1);
        
        formulaController = new FormulaController();
        dados = new String [][]{
            {"",""}
        };

        //dados = new String [][]{
        //             {"SP","Sao Paulo"},
        //             {"RJ","Rio de Janeiro"},
        //             {"RN","Rio Grande do Norte"},
        //             {"PR","Parana"}
        //};
        colunas = new String []{"Cod. Materia Prima","Quantidade"};
        // Ao inves de passar direto, colocamos os dados em um modelo
        modelo = new DefaultTableModel(colunas, 0);
        // e passamos o modelo para criar a jtable
        tbFormulaProduto.setModel( modelo );

        formulaController.inicializaObjetos();
        this.habilitaComponentes(false);
        this.txSCodigoProduto.grabFocus();
    }

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        if(getTxSCodigoProduto().getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Código do produto não informado!");
        }else{
            String msg = formulaController.validaProduto(getTxSCodigoProduto().getText());
            if(msg != null && !msg.equals("")){
                JOptionPane.showMessageDialog(rootPane, msg);
            }else{
                if(Integer.parseInt(getTxQuantidade().getValue().toString()) < 1){
                    JOptionPane.showMessageDialog(rootPane, "A quantidade não pode ser menor que [ 1 ] !");
                }else{
                    if(getTxSCodigoMateriaPrima().getText().equals("")){
                        JOptionPane.showMessageDialog(rootPane, "Código da matéria prima não informado!");
                    }else{
                        msg = formulaController.validaMateriaPrima(getTxSCodigoMateriaPrima().getText());
                        if(msg != null && !msg.equals("")){
                            JOptionPane.showMessageDialog(rootPane, msg);
                        }else{
                            String[] row = new String []{getTxSCodigoMateriaPrima().getText(),getTxQuantidade().getValue().toString()};
                            getModelo().addRow(row);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        // Obtem a linha selecionada na tabela e chama o método
        // para excluir a linha
        int linhaSelecionada = tbFormulaProduto.getSelectedRow();

        // Verificamos se existe realmente alguma linha selecionada
        if( linhaSelecionada < 0 ){
            return;
        }else{
            // Remove a linha do modelo
            formulaController.addCollectionFormulaRemoved(getModelo().getValueAt(linhaSelecionada, 0).toString());
            formulaController.removerCollectionFormula(getModelo().getValueAt(linhaSelecionada, 0).toString(), getModelo().getValueAt(linhaSelecionada, 1).toString());
            System.out.println(getModelo().getValueAt(linhaSelecionada, 0).toString());
            getModelo().removeRow(linhaSelecionada);
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void txSCodigoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txSCodigoProdutoFocusLost
        //JOptionPane.showMessageDialog(rootPane, "lost focus");
    }//GEN-LAST:event_txSCodigoProdutoFocusLost

    private void txSCodigoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSCodigoProdutoKeyPressed
        //JOptionPane.showMessageDialog(rootPane, "key pressed");
    }//GEN-LAST:event_txSCodigoProdutoKeyPressed

    private void txSCodigoProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSCodigoProdutoKeyReleased
        //JOptionPane.showMessageDialog(rootPane, "released");
    }//GEN-LAST:event_txSCodigoProdutoKeyReleased

    private void txSCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSCodigoProdutoActionPerformed
        String sCodigoProduto = this.getTxSCodigoProduto().getText();
        this.limpaComponetes();
        this.getTxSCodigoProduto().setText(sCodigoProduto);
        String msg = formulaController.validaProduto(sCodigoProduto);
        if(msg != null && !msg.equals("")){
            JOptionPane.showMessageDialog(rootPane, msg);
        }else{
            this.habilitaComponentes(true);
            this.txSCodigoMateriaPrima.grabFocus();
            ArrayList collectionFormula = new ArrayList();
            collectionFormula = formulaController.validaFormula();
            if (collectionFormula != null){
                Iterator i = collectionFormula.iterator();
                while(i.hasNext()){
                    BjFormula bjFormula = (BjFormula)i.next();
                    String[] row = new String []{bjFormula.getSCodigoMateriaPrima().getSCodigo(),bjFormula.getNQtde().toString()};
                    getModelo().addRow(row);
                }
            }

        }

    }//GEN-LAST:event_txSCodigoProdutoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Object opcoes[] = {"Sim","Não"};
        //JDialog.setDefaultLookAndFeelDecorated(true);
        int op = JOptionPane.showOptionDialog(null, "Confirma a gravação da formula?", "Gravando", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE , null, opcoes, null);
        if(op == JOptionPane.YES_OPTION ){
            formulaController.salvar(this);
        }
        //this.limpaComponetes();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        Object opcoes[] = {"Sim","Não"};
        //JDialog.setDefaultLookAndFeelDecorated(true);
        int op = JOptionPane.showOptionDialog(null, "Confirma a exclusão da formula?", "Excluindo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE , null, opcoes, null);
        if(op == JOptionPane.YES_OPTION ){

            ArrayList collectionFormula = new ArrayList();
            collectionFormula = formulaController.getCollectionFormula();
            formulaController.setCollectionFormulaRemoved(collectionFormula);

            formulaController.removerFormula();
            this.limpaComponetes();
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        this.habilitaComponentes(false);
        this.limpaComponetes();
    }//GEN-LAST:event_btNovoActionPerformed

    private void txSCodigoMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSCodigoMateriaPrimaActionPerformed
        txQuantidade.grabFocus();
    }//GEN-LAST:event_txSCodigoMateriaPrimaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroFormula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btAdd;
    private javax.swing.JToggleButton btExcluir;
    private javax.swing.JToggleButton btNovo;
    private javax.swing.JToggleButton btRemover;
    private javax.swing.JToggleButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JLabel lbSCodigoMateriaPrima;
    private javax.swing.JLabel lbSCodigoProduto;
    private javax.swing.JTable tbFormulaProduto;
    private javax.swing.JSpinner txQuantidade;
    private javax.swing.JTextField txSCodigoMateriaPrima;
    private javax.swing.JTextField txSCodigoProduto;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the txQuantidade
     */
    public javax.swing.JSpinner getTxQuantidade() {
        return txQuantidade;
    }

    /**
     * @return the txSCodigoMateriaPrima
     */
    public javax.swing.JTextField getTxSCodigoMateriaPrima() {
        return txSCodigoMateriaPrima;
    }

    /**
     * @return the txSCodigoProduto
     */
    public javax.swing.JTextField getTxSCodigoProduto() {
        return txSCodigoProduto;
    }

    /**
     * @return the modelo
     */
    public DefaultTableModel getModelo() {
        return modelo;
    }

}
