/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 24/09/2009, 14:21:42
 */

package br.com.bijufactory.ui;

import br.com.bijufactory.util.MostraRelatorio;
import java.awt.Dimension;
import java.awt.Toolkit;
import org.apache.log4j.PropertyConfigurator;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    public Main() {
        initComponents();
        PropertyConfigurator.configure("log4j.properties");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemCliente = new javax.swing.JMenuItem();
        menuItemFornecedor = new javax.swing.JMenuItem();
        menuItemFornecedorMateriaPrima = new javax.swing.JMenuItem();
        menuItemProduto = new javax.swing.JMenuItem();
        menuItemMateriaPrima = new javax.swing.JMenuItem();
        menuItemFormula = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biju Factory");
        setLocationByPlatform(true);

        jMenu1.setText("Cadastros");

        menuItemCliente.setText("Cliente");
        menuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCliente);

        menuItemFornecedor.setText("Fornecedor");
        menuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemFornecedor);

        menuItemFornecedorMateriaPrima.setText("Fornecedor Matéria Prima");
        menuItemFornecedorMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFornecedorMateriaPrimaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemFornecedorMateriaPrima);

        menuItemProduto.setText("Produtos");
        menuItemProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemProdutoMousePressed(evt);
            }
        });
        jMenu1.add(menuItemProduto);

        menuItemMateriaPrima.setText("Matéria Prima");
        menuItemMateriaPrima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemMateriaPrimaMousePressed(evt);
            }
        });
        jMenu1.add(menuItemMateriaPrima);

        menuItemFormula.setText("Formula");
        menuItemFormula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemFormulaMousePressed(evt);
            }
        });
        jMenu1.add(menuItemFormula);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Processos");

        jMenuItem4.setText("Pedido de Venda");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Mão de Obra");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relátórios");

        jMenuItem6.setText("Produtos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Pedido de Venda (NF)");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Configurações");

        jMenuItem1.setText("Tela");
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("Biju Factory");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemProdutoMousePressed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroProdutos().setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemProdutoMousePressed

    private void menuItemMateriaPrimaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemMateriaPrimaMousePressed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroMateriaPrima().setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemMateriaPrimaMousePressed

    private void menuItemFormulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemFormulaMousePressed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroFormula().setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemFormulaMousePressed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostraRelatorio();
            }
        });
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFornecedorActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroFornecedor().setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemFornecedorActionPerformed

    private void menuItemFornecedorMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFornecedorMateriaPrimaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroCotacao().setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemFornecedorMateriaPrimaActionPerformed

    private void menuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClienteActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroCliente().setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemClienteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main mainJFrame = new Main();
                //mainJFrame.setUndecorated(true);
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                mainJFrame.setBounds(0,0,screenSize.width, screenSize.height);
                mainJFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem menuItemCliente;
    private javax.swing.JMenuItem menuItemFormula;
    private javax.swing.JMenuItem menuItemFornecedor;
    private javax.swing.JMenuItem menuItemFornecedorMateriaPrima;
    private javax.swing.JMenuItem menuItemMateriaPrima;
    private javax.swing.JMenuItem menuItemProduto;
    // End of variables declaration//GEN-END:variables

}
